# Server Configuration
server.port=8080
spring.application.name=morocco-real-estate

# Database Configuration
spring.datasource.url=jdbc:postgresql://ep-cold-truth-ape1wejg.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_mb6xeiUAOp8d
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=jdbc:postgresql://localhost:5432/morocco_real_estate
#spring.datasource.username=postgres
#spring.datasource.password=postgres

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# SQL Initialization
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.jpa.defer-datasource-initialization=true

# JWT Configuration
jwt.secret=MoroccoRealEasteSecretKey2024ForJWTTokenGeneration
jwt.expiration=86400000

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# CORS Configuration
cors.allowed-origins=http://localhost:4200
